### ISSUE TITLE
The render-string example doesn't work

### ISSUE THREAD

**Issue by weavejester** [mylesmegyesi/sass-clojure#5]
```clojure
(render-string "$blue: #3bbfce; .content-navigation { border-color: $blue; }")
```

This produces an exception. I suspect this is because it defaults to parsing sass, rather than scss. Setting the `:syntax :scss` option doesn't work either, and there doesn't seem to be code in the source file to make this work.

**Comment by mylesmegyesi** [comment]
Thanks for the heads up @weavejester. This library has a considerable amount of dust collected. Since the time that I originally wrote it, `libsass` has become a thing and has a [Java bridge](https://github.com/bit3/jsass). Now that there is no need to use the RubyGem with JRuby, I don't feel this library really provides any value over the Java bridge. I'd suggest you just use it directly.

**Comment by weavejester** [comment]
Thanks. I've already started looking at that :)
